services:
  - type: web
    name: proflix
    env: node
    branch: main
    buildCommand: ./build.sh
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: NODE_ENV
        value: production 