services:
  - type: web
    name: proflix-app
    runtime: node
    plan: starter
    buildCommand: ./render-build.sh
    startCommand: ./render-start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: proflix-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false

databases:
  - name: proflix-db
    plan: free